### ISSUE TITLE
[15%] Create HTML pages for seller interface

### ISSUE THREAD

**Issue by FlorenceMei** [CCPX-system/CCPX-webapplication#3]
business_information : Florence
modify_information : Flo
Static center: Flo

pay fee: Helen done

intelligent_query : Sardor
search criteria: Sardor

exchange_points : Luna
Transfer points: Luna

manage advertisement : Artem 

exchange_rate : working (quentin)
trading_chart_points : still working on it (quentin)
// trading_chart_times : for me it's the same as "trading_chart_point" (quentin) ???

login : done (same as user website)
reset password :  same as user website
registration : finished (quentin)
Homepage: done (Quentin)

**Comment by quentinlegaux** [comment]
look at the protype (from seller group) in "Documentation" directory.
It should help us to create the pages for seller website ;)

**Comment by quentinlegaux** [comment]
[protype8.0(sellergroup).zip](https://github.com/CCPX-system/CCPX-webapplication/files/601370/protype8.0.sellergroup.zip)

**Comment by FlorenceMei** [comment]
last commit https://github.com/CCPX-system/CCPX-webapplication/commit/c6b29c69c258026f9bf94c20ab490952d63701da
